ProjectDanceBundle:
    resource: "@ProjectDanceBundle/Controller/"
    type:     annotation
    prefix:   /dance
    
login:
    pattern: /login
    type:     annotation
    defaults: { _controller: ProjectDanceBundle:Default:login }
login_check:
    pattern: /login_check

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
