ProjectDataBundle:
    resource: "@ProjectDataBundle/Controller/"
    type:     annotation
    prefix:   /

ProjectDanceBundle:
    resource: "@ProjectDanceBundle/Controller/"
    type:     annotation
    prefix:   /dance
main:
    pattern: /dance
    
    
login:
    pattern: /login
    type:     annotation
    defaults: { _controller: ProjectDanceBundle:Default:login }
login_check:
    pattern: /login_check
register:
    pattern: /register
    type:     annotation
    defaults: { _controller: ProjectDataBundle:Default:registration }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
