security:
    providers:
        main:
            entity: { class: Project\DataBundle\Entity\User, property: username }
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                qqq: { password: qqq, roles: [ 'ROLE_QQQ' ] }
    encoders:
        Project\DataBundle\Entity\User: sha512

    firewalls:
        secured_area:
            security: true
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /project/hello
    access_control:
        - { path: ^/dance/, roles: ROLE_USER }
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
